angular.module('BigBoomApp.Store').constant('ARTICLE_CONSTANT', {
  MODULE_URL:'store/article',
  SWEET_ALERT_CONFIRM_BUTTON_COLOR: '#DD6B55',
  IM_SURE: 'LABEL.IM_SURE',
  DO_YOU_WANT_REMOVE_THIS_ARTICLE: 'LABEL.DO_YOU_WANT_REMOVE_THIS_ARTICLE',
  DO_YOU_WANT_REMOVE_THIS_COMMENT: 'LABEL.DO_YOU_WANT_REMOVE_THIS_COMMENT',
  ARE_YOU_SURE:'LABEL.ARE_YOU_SURE',
  SWEET_ALERT_TYPE:'warning'
});
