angular.module('BigBoomApp.Store').constant('MENU_CONSTANT', {
  MODULE_MENU_URL:'store/menu',
  MODULE_FOOD_URL:'store/food',
  SWEET_ALERT_CONFIRM_BUTTON_COLOR: '#DD6B55',
  IM_SURE: 'LABEL.IM_SURE',
  DO_YOU_WANT_REMOVE_THIS_MENU: 'LABEL.DO_YOU_WANT_REMOVE_THIS_MENU',
  DO_YOU_WANT_REMOVE_THIS_FOOD: 'LABEL.DO_YOU_WANT_REMOVE_THIS_FOOD',
  DO_YOU_WANT_REMOVE_THIS_COMMENT: 'LABEL.DO_YOU_WANT_REMOVE_THIS_COMMENT',
  ARE_YOU_SURE:'LABEL.ARE_YOU_SURE',
  SWEET_ALERT_TYPE:'warning'
});
